export const titlesPrefix = [
  'Designer',
  'Manager',
  'Assistant',
  'Engineer',
  'Support',
  'Sales',
  'Shipping',
];

export const tasks = [
  { ID: 1, AssigneeID: 6, Task: 'Refactor code to improve maintainability' },
  { ID: 2, AssigneeID: 11, Task: 'Update documentation for API endpoints' },
  { ID: 3, AssigneeID: 3, Task: 'Fix UI bugs reported by QA team' },
  { ID: 4, AssigneeID: 8, Task: 'Create automated deployment scripts' },
  { ID: 5, AssigneeID: 14, Task: 'Implement pagination for large datasets' },
  { ID: 6, AssigneeID: 2, Task: 'Integrate third-party API for payment processing' },
  { ID: 7, AssigneeID: 5, Task: 'Implement user authentication functionality' },
  { ID: 8, AssigneeID: 9, Task: 'Deploy application to staging environment' },
  { ID: 9, AssigneeID: 10, Task: 'Design and develop new feature based on requirements' },
  { ID: 10, AssigneeID: 13, Task: 'Write unit tests for new features' },
  { ID: 11, AssigneeID: 4, Task: 'Optimize database queries for better performance' },
  { ID: 12, AssigneeID: 7, Task: 'Conduct performance testing and analysis' },
  { ID: 13, AssigneeID: 12, Task: 'Conduct code review for pull request #123' },
  { ID: 14, AssigneeID: 1, Task: 'Perform security audit and implement fixes' },
  { ID: 15, AssigneeID: 6, Task: 'Create mockups for upcoming feature' },
  { ID: 16, AssigneeID: 8, Task: 'Optimize frontend assets for faster loading times' },
  { ID: 17, AssigneeID: 3, Task: 'Configure CI/CD pipeline for automated testing' },
  { ID: 18, AssigneeID: 11, Task: 'Investigate and resolve server downtime issue' },
  { ID: 19, AssigneeID: 2, Task: 'Provide technical support to end-users' },
  { ID: 20, AssigneeID: 7, Task: 'Implement error logging and monitoring' },
];

export const employees = [
  {
    ID: 1,
    FullName: 'John Heart',
    Prefix: 'Mr.',
    Position: 'CTO',
    City: 'Glendale',
    State: 'California',
  },
  {
    ID: 2,
    FullName: 'Olivia Peyton',
    Prefix: 'Mrs.',
    Position: 'HR Manager',
    City: 'Glendale',
    State: 'California',
  },
  {
    ID: 3,
    FullName: 'Robert Reagan',
    Prefix: 'Mr.',
    Position: 'IT Manager',
    City: 'Jacksonville',
    State: 'Arkansas',
  },
  {
    ID: 4,
    FullName: 'Greta Sims',
    Prefix: 'Ms.',
    Position: 'Shipping Manager',
    City: 'Avondale',
    State: 'Arizona',
  },
  {
    ID: 5,
    FullName: 'Brett Wade',
    Prefix: 'Mr.',
    Position: 'Shipping Manager',
    City: 'Buckeye',
    State: 'Arizona',
  },
  {
    ID: 6,
    FullName: 'Sandra Johnson',
    Prefix: 'Mrs.',
    Position: 'Network Admin',
    City: 'Fairbanks',
    State: 'Alaska',
  },
  {
    ID: 7,
    FullName: 'Kevin Carter',
    Prefix: 'Mr.',
    Position: 'Network Admin',
    City: 'Dothan',
    State: 'Alabama',
  },
  {
    ID: 8,
    FullName: 'Cynthia Stanwick',
    Prefix: 'Ms.',
    Position: 'Sales Assistant',
    City: 'Dothan',
    State: 'Alabama',
  },
  {
    ID: 9,
    FullName: 'Kent Samuelson',
    Prefix: 'Dr.',
    Position: 'Sales Assistant',
    City: 'Hoover',
    State: 'Alabama',
  },
  {
    ID: 10,
    FullName: 'Taylor Riley',
    Prefix: 'Mr.',
    Position: 'Support Assistant',
    City: 'Glendale',
    State: 'California',
  },
  {
    ID: 11,
    FullName: 'Sam Hill',
    Prefix: 'Mr.',
    Position: 'Sales Assistant',
    City: 'Anchorage',
    State: 'Alaska',
  },
  {
    ID: 12,
    FullName: 'Kelly Rodriguez',
    Prefix: 'Ms.',
    Position: 'Sales Assistant',
    City: 'Glendale',
    State: 'California',
  },
  {
    ID: 13,
    FullName: 'Natalie Maguirre',
    Prefix: 'Mrs.',
    Position: 'Sales Assistant',
    City: 'Jacksonville',
    State: 'Arkansas',
  },
  {
    ID: 14,
    FullName: 'Walter Hobbs',
    Prefix: 'Mr.',
    Position: 'Support Assistant',
    City: 'Anchorage',
    State: 'Alaska',
  },
];

export const states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California'];
